# InfiniBand OpenSM - Subnet Manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ib-opensm
  name: ib-opensm
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ib-opensm
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ib-opensm
    spec:
      containers:
      - image: ghcr.io/ananace/container-opensm:master
        imagePullPolicy: Always
        name: opensm
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
        securityContext:
          privileged: true
      nodeSelector:
        kubernetes.io/os: linux
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: ib-opensm
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
